# Site settings
title: Your Site Title
description: This guide will help you 
  - Understand how photo search works  
  - Learn common mistakes and how to fix them  
  - Use filters to narrow results  
  - Stay organized so searching is easier in the future.

baseurl: "/fva-helpers" # The subpath of your site, e.g. /blog
url: "https://dimanikulin.github.io/fva-helpers/" # The base hostname & protocol for your site

# Build settings
markdown: kramdown # You can choose other markdown renderers like GFM
theme: jekyll-theme-minimal # Specifies the Jekyll theme to use
plugins:
  - jekyll-feed # Example of a Jekyll plugin
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
